server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-service
  cloud:
    discovery:
      enabled: true
      client:
        simple:
          local:
            service-id: auth-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000