server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

  cloud:
    discovery:
      enabled: true
      client:
        simple:
          local:
            service-id: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/common_db?currentSchema=notification_schema
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: notification_schema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default_schema: notification_schema

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: usmanova.al.v@gmail.com
    password: Kofekofe08091965
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  server-url: http://localhost:8081
  client-id: service-client
  client-secret: service-secret

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000