server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  cloud:
    discovery:
      enabled: true
      client:
        simple:
          local:
            service-id: order-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        acks: all
        auto.create.topics.enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/common_db?currentSchema=order_schema
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: order_schema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default_schema: order_schema

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000