server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  cloud:
    discovery:
      enabled: true
      client:
        simple:
          local:
            service-id: product-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/common_db?currentSchema=product_schema
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: product_schema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default_schema: product_schema

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

aws:
  s3:
    bucket-name: your-bucket-name
    region: us-east-1
    access-key: your-access-key
    secret-key: your-secret-key